# Generated by Django 5.1.1 on 2025-03-18 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempuserprofile',
            old_name='contact_info',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='tempuserprofile',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='employment_type',
        ),
        migrations.AddField(
            model_name='tempuserprofile',
            name='email',
            field=models.CharField(default='user@server,com', max_length=100),
        ),
        migrations.AddField(
            model_name='tempuserprofile',
            name='employment',
            field=models.CharField(choices=[('Salaried', 'Salaried'), ('Business', 'Business')], default='Salaried', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='user@server,com', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment',
            field=models.CharField(choices=[('Salaried', 'Salaried'), ('Business', 'Business')], default='Salaried', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AlterField(
            model_name='tempuserprofile',
            name='address',
            field=models.TextField(default='flat no. 123, street 456, city, state, country'),
        ),
        migrations.AlterField(
            model_name='tempuserprofile',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='tempuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='flat no. 123, street 456, city, state, country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
