# Generated by Django 5.1.1 on 2025-03-18 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_contact_info_tempuserprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreport',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='tempuserprofile',
            name='phone',
            field=models.CharField(default='1234567890', max_length=100),
        ),
    ]
