# Generated by Django 5.1.1 on 2025-03-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_taxreport_profile_alter_tempuserprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxreport',
            name='profile',
        ),
        migrations.AlterField(
            model_name='housepropertyincome',
            name='Are_Properties_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tempuserprofile',
            name='email',
            field=models.EmailField(default='user@server.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='user@server.com', max_length=254),
        ),
    ]
