# Generated by Django 5.1.1 on 2025-03-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_taxreport_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreport',
            name='deductions_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
